services:
  node_a:
    build: .
    volumes:
      - ./docker-input/node_a_input.sh:/usr/local/bin/node_input.sh
    command: sh -c 'chmod +x /usr/local/bin/node_input.sh && /usr/local/bin/node_input.sh | priory'
    networks:
      - firewall_a
  node_b:
    build: .
    volumes:
      - ./docker-input/node_b_input.sh:/usr/local/bin/node_input.sh
    command: sh -c 'chmod +x /usr/local/bin/node_input.sh && /usr/local/bin/node_input.sh | priory'
    networks:
      - firewall_a
      - firewall_c
  node_c:
    build: .
    volumes:
      - ./docker-input/node_c_input.sh:/usr/local/bin/node_input.sh
    command: sh -c 'chmod +x /usr/local/bin/node_input.sh && /usr/local/bin/node_input.sh | priory'
    networks:
      - firewall_c
  node_d:
    build: .
    volumes:
      - ./docker-input/node_d_input.sh:/usr/local/bin/node_input.sh
    command: sh -c 'chmod +x /usr/local/bin/node_input.sh && /usr/local/bin/node_input.sh | priory'
    networks:
      - firewall_c

networks:
  firewall_a:
    internal: true
  firewall_c:
    internal: true
