port = 0
is_relay = true
name = "joss!"
secret_key_seed = 1
relay_address = "/ip4/142.93.53.125/tcp/4001/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN"
peers = "12D3KooWQYhTNQdmr3ArTeUHRYzFg94BKyTkoWBDWez9kSCVe2Xo"

[num_gossipsub_connections]
target_num = 7
lower_tolerance = 2
upper_tolerance = 5
