port = 0
is_relay = true
secret_key_seed = 1
peers = [
	{ multiaddr = "/ip4/127.0.0.1/tcp/4001", peer_id = "12D3KooWQYhTNQdmr3ArTeUHRYzFg94BKyTkoWBDWez9kSCVe2Xo" },
]

[num_gossipsub_connections]
target_num = 7
lower_tolerance = 2
upper_tolerance = 5
